name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: go test ./...

  docker:
    if: "!contains(github.event.head_commit.message, 'skip docker build')"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dioptra-io/publish-docker-action@v1
        with:
          file: ./Dockerfile
          image: dioptra-io/retina-orchestrator
          password: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ github.event_name == 'push' && github.actor != 'dependabot[bot]' }}
